#!/bin/bash
#
# For VMs that have name labels matching regular expression, set VDI's
# name label to match VM's name label.
#

REGEX='^p[0-9]{5}'

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

for VM_UUID in $(get_uuids vm ""); do
    echo -e "VM UUID: $VM_UUID"
    VM_NAME_LABEL=$(get_param vm "$VM_UUID" name-label)
    if [[ "$VM_NAME_LABEL" =~ $REGEX ]]; then
        echo "VM name label: $VM_NAME_LABEL"
        VDI_UUID=$(xe vbd-list params=vdi-uuid userdevice=0 vm-uuid=$VM_UUID --minimal) || continue
        echo "VDI UUID: $VDI_UUID"
        echo -e "Renaming VDI...\c"
        if set_params vdi "$VDI_UUID" name-label "$VM_NAME_LABEL"; then
            echo "done."
        else
            echo
        fi
    fi
done
