#!/bin/bash

function usage() {
    cat <<EOF
Usage: ${0##*/} -v VM -n NETWORK -d DEVICE [-m MACADDRESS]

-v    name label of the VM
-n    name label of the network
-d    number of eth device (0-15)
-m    MAC address of eth device
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

while getopts :v:n:d:m: OPT; do
    case $OPT in
        v)
            VM="$OPTARG"
            ;;
        n)
            NETWORK="$OPTARG"
            ;;
        d)
            DEVICE="$OPTARG"
            ;;
        m)
            MACADDRESS="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[ -n "$1" ] && usage
REQUIRED=( "VM" "NETWORK" "DEVICE" )
have_required "${REQUIRED[@]}" || usage

if [ -n "$MACADDRESS" ]; then
    if ! valid_mac_address "$MACADDRESS"; then
        echo -e "Invalid MAC address."
        exit 1
    fi
else
    MACADDRESS="random"
fi

get_uuids vm "$VM" || exit 1
VM_UUID=${UUIDS[0]}
echo "VM UUID: $VM_UUID"
get_uuids network "$NETWORK" || exit 1
NETWORK_UUID=${UUIDS[0]}
echo "Network UUID: $NETWORK_UUID"

CMD="xe vif-create device=$DEVICE mac=$MACADDRESS network-uuid=$NETWORK_UUID vm-uuid=$VM_UUID"
VIF_UUID=$($CMD) && echo "VIF UUID: $VIF_UUID"
