#!/bin/bash

function usage() {
    cat <<EOF

Destroy all of a VM's VIFs.

Usage: ${0##*/} [-f] -v VM

-f    destroy without prompting
-v    name label of the VM
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

FORCE=0
unset VM
while getopts :fv: OPT; do
    case $OPT in
        f)
            FORCE=1
            ;;
        v)
            VM="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
have_required VM || usage

VM_UUID=$(get_uuid vm "$VM") || exit 1
echo "VM UUID: $VM_UUID"

VIF_UUIDS=$(xe vif-list vm-uuid="$VM_UUID" --minimal)
for VIF_UUID in ${VIF_UUIDS//,/ }; do
    echo -e "\nVIF UUID: $VIF_UUID"
    if ! (( FORCE )); then
        DEVICE=$(get_param vif "$VIF_UUID" device) || continue
        prompt "Destroy device $DEVICE" || continue
    fi
    echo -e "Destroying VIF...\c"
    if destroy vif "$VIF_UUID"; then
        echo "done."
    else
        exit 1
    fi
done
