#!/bin/bash

function usage() {
    cat <<EOF

Perform a live VM migration.

Usage: ${0##*/} [-l] -h HOST -v VM

-l    use local storage on destination host
-h    name label (host name) of XenServer host to which to migrate the VM
-v    name label of the VM
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

LOCAL=0

while getopts :lh:v: OPT; do
    case $OPT in
        l)
            LOCAL=1
            ;;
        h)
            HOST="$OPTARG"
            ;;
        v)
            VM="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[ -n "$1" ] && usage
REQUIRED=( "HOST" "VM" )
have_required "${REQUIRED[@]}" || usage

get_uuid host "$HOST" || exit 1
HOST_UUID="$UUID"
echo "Host UUID: $HOST_UUID"

if (( LOCAL )); then
    get_local_sr_uuid "$HOST" || exit 1
    echo "SR UUID: $SR_UUID"
fi

get_uuid vm "$VM" || exit 1
VM_UUID="$UUID"
echo "VM UUID: $VM_UUID"

if (( LOCAL )); then
    xe vm-migrate live=true remote-master="$XE_SERVER" remote-username="$XE_USERNAME" remote-password="$XE_PASSWORD" destination-sr-uuid="$SR_UUID" host-uuid="$HOST_UUID" vm="$VM_UUID"
else
    xe vm-migrate live=true host-uuid="$HOST_UUID" vm="$VM_UUID"
fi
