#!/bin/bash

function usage() {
    cat <<EOF
Usage: ${0##*/} -p PIF -v VLAN -n NETWORK [-d DESCRIPTION]

-p    name label of PIF (physical interface) that supports the desired VLAN
-v    ID (tag) of the new VLAN
-n    name label of the new network
-d    name description of the new network
EOF
    exit 2
}

# get PIF UUID from device name (optional VLAN arg); set global
# PIF_UUID
function pif_uuid() {
    [ -z "$1" ] && return 1
    local PIF="$1" VLAN="${2--1}"
    local PIF_UUID=$(xe pif-list device="$PIF" VLAN="$VLAN" --minimal)
    if [ -z "$PIF_UUID" ]; then
        (( QUIET )) || echo "Found no matching PIFs."
        return 1
    else
        echo "$PIF_UUID"
        return 0
    fi
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

while getopts :p:v:n:d: OPT; do
    case $OPT in
        p)
            PIF="$OPTARG"
            ;;
        v)
            VLAN="$OPTARG"
            ;;
        n)
            NETWORK="$OPTARG"
            ;;
        d)
            DESCRIPTION="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[ -n "$1" ] && usage
have_required PIF VLAN NETWORK || usage

PIF_UUID=$(pif_uuid "$PIF") || exit 1
echo "PIF UUID: $PIF_UUID"

NETWORK_UUID=$(xe network-create name-label="$NETWORK" name-description="$DESCRIPTION") || exit 1
echo "Network UUID: $NETWORK_UUID"
VLAN_UUID=$(xe vlan-create pif-uuid="$PIF_UUID" network-uuid="$NETWORK_UUID" vlan="$VLAN") || exit 1
echo "VLAN UUID: $VLAN_UUID"
