#!/bin/bash

function usage() {
    cat <<EOF
Usage: ${0##*/} -p PIF -v VLAN -n NETWORK [-d DESCRIPTION]

-p    name label of PIF (physical interface) that supports the desired VLAN
-v    ID (tag) of the new VLAN
-n    name label of the new network
-d    name description of the new network
EOF
    exit 2
}

while getopts :p:v:n:d: OPT; do
    case $OPT in
        p)
            PIF="$OPTARG"
            ;;
        v)
            VLAN="$OPTARG"
            ;;
        n)
            NETWORK="$OPTARG"
            ;;
        d)
            DESCRIPTION="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[ -n "$1" ] && usage
[ -z "$PIF" ] || [ -z "$VLAN" ] || [ -z "$NETWORK" ] && usage

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

pif_uuid "$PIF" || exit 1
echo "PIF UUID: $PIF_UUID"

NETWORK_UUID=$(xe network-create name-label="$NETWORK" name-description="$DESCRIPTION")
if [ -n "$NETWORK_UUID" ]; then
    echo "Network UUID: $NETWORK_UUID"
    VLAN_UUID=$(xe vlan-create pif-uuid="$PIF_UUID" network-uuid="$NETWORK_UUID" vlan="$VLAN")
    if [ -n "$VLAN_UUID" ]; then
        echo "VLAN UUID: $VLAN_UUID"
    else
        exit 1
    fi
else
    exit 1
fi
