#!/bin/bash

function usage() {
    cat <<EOF

Perform a live VM migration to another host in the same pool.

Usage: ${0##*/} [-l] -h HOST VM

-l    use local storage on destination host
-h    name label (host name) of XenServer host to which to migrate the VM
VM    name label of the VM
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

LOCAL=0

while getopts :lh: OPT; do
    case $OPT in
        l)
            LOCAL=1
            ;;
        h)
            HOST="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
VM="$1"
shift
[ -n "$1" ] && usage
have_required HOST VM || usage

HOST_UUID=$(get_uuid host "$HOST") || exit 1
echo "Host UUID: $HOST_UUID"

if (( LOCAL )); then
    SR_UUID=$(get_uuid sr "Local storage" host "$HOST") || exit 1
    echo "SR UUID: $SR_UUID"
fi

VM_UUID=$(get_uuid vm "$VM") || exit 1
echo "VM UUID: $VM_UUID"

if (( LOCAL )); then
    xe vm-migrate live=true remote-master="$XE_SERVER" remote-username="$XE_USERNAME" remote-password="$XE_PASSWORD" destination-sr-uuid="$SR_UUID" host-uuid="$HOST_UUID" vm="$VM_UUID"
else
    xe vm-migrate live=true host-uuid="$HOST_UUID" vm="$VM_UUID"
fi
