#!/bin/bash

function usage() {
    cat <<EOF

Enable or disable optional QEMU timers that affect load on dom0.
Default is to disable.

Usage: ${0##*/} [-e] -v VM { [-s] [-p] [-u] }

-e    enable timers
-v    name label of the VM
-s    set serial port emulation
-p    set parallel port emulation
-u    set USB emulation
EOF
    exit 2
}

DISABLE=1
ENABLE=0
SERIAL=0
PARALLEL=0
USB=0

while getopts :ev:spu OPT; do
    case $OPT in
        e)
            DISABLE=0
            ;;
        v)
            VM="$OPTARG"
            ;;
        s)
            SERIAL=1
            ;;
        p)
            PARALLEL=1
            ;;
        u)
            USB=1
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[[ $(( SERIAL + PARALLEL + USB )) -eq 0 ]] && usage

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

get_uuid vm "$VM" || exit 1
VM_UUID="$UUID"
echo "VM UUID: $VM_UUID"

if (( SERIAL )); then
    (( DISABLE )) && NONE="none"
    ARGS="hvm_serial $NONE"
    unset NONE
fi
if (( PARALLEL )); then
    (( DISABLE )) && NONE="none"
    ARGS="$ARGS parallel $NONE"
fi
if (( USB )); then
    (( DISABLE )) && FALSE="false"
    ARGS="$ARGS usb $FALSE usb_tablet $FALSE"
fi

if (( DISABLE )); then
    FUNCTION=set_map_keys
else
    FUNCTION=remove_map_keys
fi
eval $FUNCTION vm "$VM_UUID" platform $ARGS
