#!/bin/bash

function usage() {
    cat <<EOF

Set a VM's memory parameters.

Usage: ${0##*/} -s STATIC_MIN -S STATIC_MAX -d DYNAMIC_MIN -D DYNAMIC_MAX -v VM
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

while getopts :s:S:d:D:v: OPT; do
    case $OPT in
        s)
            STATIC_MIN="$OPTARG"
            ;;
        S)
            STATIC_MAX="$OPTARG"
            ;;
        d)
            DYNAMIC_MIN="$OPTARG"
            ;;
        D)
            DYNAMIC_MAX="$OPTARG"
            ;;
        v)
            VM="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[ -n "$1" ] && usage
REQUIRED=( "STATIC_MIN" "STATIC_MAX" "DYNAMIC_MIN" "DYNAMIC_MAX" "VM" )
have_required "${REQUIRED[@]}" || usage

get_uuids vm "$VM" || exit 1
VM_UUID="${UUIDS[0]}"
echo "VM UUID: $VM_UUID"

set_params vm "$VM_UUID" \
    memory-static-max "$STATIC_MAX" \
    memory-dynamic-max "$DYNAMIC_MAX" \
    memory-dynamic-min "$DYNAMIC_MIN" \
    memory-static-min "$STATIC_MIN"
