#!/bin/bash

function usage() {
    cat <<EOF

Toggle a VM's "is-a-template" parameter.

Usage: ${0##*/} [-s] VM

-s    show the status of the VM's "is-a-template" parameter but don't modify
VM    name label of the VM to be modified
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

SHOW=0

while getopts :s OPT; do
    case $OPT in
        s)
            SHOW=1
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[ -z "$1" ] || [ $# -gt 1 ] && usage
VM="$1"

if VM_UUID=$(get_uuid vm "$VM"); then
    if (( SHOW )); then
        IS="is not"
    else
        if set_params vm "$VM_UUID" is-a-template true; then
            IS="now is"
        else
            exit 1
        fi
    fi
elif TEMPLATE_UUID=$(get_uuid template "$VM"); then
    if (( SHOW )); then
        IS="is"
    else
        if set_params vm "$TEMPLATE_UUID" is-a-template false; then
            IS="now is not"
        else
            exit 1
        fi
    fi
else
    exit 1
fi

echo "$VM $IS a template."
