#!/bin/bash
#
# This script assumes a rescue boot via network.
#

ADD_ARGS="ks=http://10.1.0.1/linux-install/centos/centos-rescue.ks rescue"

function usage() {
    cat <<EOF

Toggle a VM's "PV-args" and "PV-bootloader" parameters between network
rescue boot and regular boot.

Usage: ${0##*/} VM

VM    name label of the VM to be modified
EOF
    exit 2
}

[ -z "$1" ] || [ "$#" -gt 1 ] && usage
VM="$1"

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

get_uuids vm "$VM" || exit 1
VM_UUID="${UUIDS[0]}"
echo "VM UUID: $VM_UUID"
get_param vm PV-args "$VM_UUID"
PV_ARGS="$PARAM_VALUE"
if [[ "$PV_ARGS" =~ $ADD_ARGS ]]; then
    echo -e "Disabling network rescue boot...\c"
    PV_ARGS=${PV_ARGS/$ADD_ARGS/}
    CMD="xe vm-param-set PV-args=\"$PV_ARGS\" PV-bootloader=pygrub uuid=$VM_UUID"
else
    echo -e "Enabling network rescue boot...\c"
    PV_ARGS="$PV_ARGS $ADD_ARGS"
    CMD="xe vm-param-set PV-args=\"$PV_ARGS\" PV-bootloader=eliloader uuid=$VM_UUID"
fi
if eval "$CMD"; then
    echo "done."
else
    exit 1
fi
