#!/bin/bash

function usage() {
    cat <<EOF

Show the VLAN tags of the bridges of the PIFs of the networks of the VM's VIFs.

Usage: ${0##*/} VM

VM    name label of the VM to be inspected
EOF
    exit 2
}

[ -z "$1" ] || [ $# -gt 1 ] && usage
VM="$1"

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

get_uuid vm "$VM" || exit 1
VM_UUID="$UUID"
echo "VM UUID: $VM_UUID"
get_uuids vif "" vm-uuid "$VM_UUID"
VIF_UUIDS=( ${UUIDS[*]} )
for VIF_UUID in ${VIF_UUIDS[@]}; do
    get_param vif device "$VIF_UUID"
    VIF_DEVICE="$PARAM_VALUE"
    vif_network_uuid "$VIF_UUID"
    PIF_VLAN=$(xe pif-list params=VLAN network-uuid="$NETWORK_UUID" --minimal)
    echo "$VIF_DEVICE: VLAN $PIF_VLAN"
done
