#!/bin/bash

ADD_ARGS="ks=http://10.1.0.1/linux-install/centos/centos-rescue.ks rescue"

function usage() {
    cat <<EOF

Toggle a VM's "PV-args" and "PV-bootloader" parameters between network
rescue boot and regular boot.

Usage: ${0##*/} VM

VM    name label of the VM to be modified
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

VM="$1"
have_required VM || usage

VM_UUID=$(get_uuid vm "$VM") || exit 1
echo "VM UUID: $VM_UUID"
PV_ARGS=$(get_param vm "$VM_UUID" PV-args)
if [[ "$PV_ARGS" =~ $ADD_ARGS ]]; then
    echo -e "Disabling network rescue boot...\c"
    PV_ARGS=${PV_ARGS/$ADD_ARGS/}
    PV_ARGS=$(echo $PV_ARGS)  # use word-splitting to collapse spaces
    PV_BOOTLOADER="pygrub"
else
    echo -e "Enabling network rescue boot...\c"
    PV_ARGS=$(echo $PV_ARGS $ADD_ARGS)  # use word-splitting to collapse spaces
    PV_BOOTLOADER="eliloader"
fi
if set_params vm "$VM_UUID" PV-args "$PV_ARGS" PV-bootloader "$PV_BOOTLOADER"; then
    echo "done."
else
    exit 1
fi
