#!/bin/bash

function usage() {
    cat <<EOF

Toggle a VM's "PV-args" parameter between between single-user boot and
regular boot.

Usage: ${0##*/} VM

VM    name label of the VM to be modified
EOF
    exit 2
}

[ -z "$1" ] || [ "$#" -gt 1 ] && usage
VM="$1"

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

get_uuids vm "$VM" || exit 1
VM_UUID="${UUIDS[0]}"
echo "VM UUID: $VM_UUID"
get_param vm PV-args "$VM_UUID"
PV_ARGS="$PARAM_VALUE"
if [[ "$PV_ARGS" =~ single ]]; then
    echo -e "Disabling single-user boot...\c"
    PV_ARGS=${PV_ARGS/single/}
else
    echo -e "Enabling single-user boot...\c"
    PV_ARGS=$(echo $PV_ARGS single) # use word-splitting to collapse spaces
fi
CMD="xe vm-param-set PV-args=\"$PV_ARGS\" uuid=$VM_UUID"
if eval "$CMD"; then
    echo "done."
else
    exit 1
fi
