#!/bin/bash


function usage() {
    cat <<EOF

Set a VM's VCPU parameters.

Usage: ${0##*/} -m VCPUS_MAX -s VCPUS_AT_STARTUP VM
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

while getopts :m:s: OPT; do
    case $OPT in
        m)
            VCPUS_MAX="$OPTARG"
            ;;
        s)
            VCPUS_AT_STARTUP="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
VM="$1"
shift
[ -n "$1" ] && usage
have_required VM VCPUS_MAX VCPUS_AT_STARTUP || usage

VM_UUID=$(get_uuid vm "$VM") || exit 1
echo "VM UUID: $VM_UUID"

CURRENT_MAX=$(get_param vm "$VM_UUID" VCPUs-max) || exit 1
if [ "$VCPUS_AT_STARTUP" -gt "$CURRENT_MAX" ]; then
    ARGS="VCPUs-max $VCPUS_MAX VCPUs-at-startup $VCPUS_AT_STARTUP"
else
    ARGS="VCPUs-at-startup $VCPUS_AT_STARTUP VCPUs-max $VCPUS_MAX"
fi
set_params vm "$VM_UUID" $ARGS
