#!/bin/bash

function usage() {
    cat <<EOF

Toggle a VM's "is-a-template" parameter.

Usage: ${0##*/} [-s] VM

-s    show the status of the VM's "is-a-template" parameter but don't modify
VM    name label of the VM to be modified
EOF
    exit 2
}

SHOW=0

while getopts :s OPT; do
    case $OPT in
        s)
            SHOW=1
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[ -z "$1" ] || [ "$#" -gt 1 ] && usage
VM="$1"

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

QUIET=1 uuids vm "$VM"
case $? in
    0)
        if (( SHOW )); then
            IS="is not"
        else
            if xe vm-param-set is-a-template=true uuid="${UUIDS[0]}"; then
                IS="now is"
            else
                exit 1
            fi
        fi
        ;;
    1)
        uuids template "$VM" || exit 1
        if (( SHOW )); then
            IS="is"
        else
            if xe template-param-set is-a-template=false uuid="${UUIDS[0]}"; then
                IS="now is not"
            else
                exit 1
            fi
        fi
        ;;
    2)
        uuids vm "$VM"  # because first vm_uuid() call suppressed output
        exit 1
        ;;
    *)
        exit $?
esac

echo "$VM $IS a template."
