#!/bin/bash

function usage() {
    cat <<EOF

Enable or disable optional QEMU timers that affect load on dom0.
Default is to disable.

Usage: ${0##*/} [-e] { [-s] [-p] [-u] } VM

-e    enable timers
-s    set serial port emulation
-p    set parallel port emulation
-u    set USB emulation
VM    name label of the VM
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

DISABLE=1
ENABLE=0
SERIAL=0
PARALLEL=0
USB=0

while getopts :espu OPT; do
    case $OPT in
        e)
            DISABLE=0
            ;;
        s)
            SERIAL=1
            ;;
        p)
            PARALLEL=1
            ;;
        u)
            USB=1
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
VM="$1"
shift
[ -n "$1" ] && usage
have_required VM && [ $(( SERIAL + PARALLEL + USB )) -gt 0 ] || usage

VM_UUID=$(get_uuid vm "$VM") || exit 1
echo "VM UUID: $VM_UUID"

if (( SERIAL )); then
    (( DISABLE )) && NONE="none"
    ARGS="hvm_serial $NONE"
    unset NONE
fi
if (( PARALLEL )); then
    (( DISABLE )) && NONE="none"
    ARGS="$ARGS parallel $NONE"
fi
if (( USB )); then
    (( DISABLE )) && FALSE="false"
    ARGS="$ARGS usb $FALSE usb_tablet $FALSE"
fi

if (( DISABLE )); then
    FUNCTION=set_map_keys
else
    FUNCTION=remove_map_keys
fi
eval $FUNCTION vm "$VM_UUID" platform $ARGS
