#!/bin/bash

function usage() {
    cat <<EOF

Toggle a VM's "PV-args" parameter between between single-user boot and
regular boot.

Usage: ${0##*/} VM

VM    name label of the VM to be modified
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

[ -z "$1" ] || [ $# -gt 1 ] && usage
VM="$1"

VM_UUID=$(get_uuid vm "$VM") || exit 1
echo "VM UUID: $VM_UUID"
PV_ARGS=$(get_param vm "$VM_UUID" PV-args)
if [[ "$PV_ARGS" =~ single ]]; then
    echo -e "Disabling single-user boot...\c"
    PV_ARGS=${PV_ARGS/single/}
    PV_ARGS=$(echo $PV_ARGS)  # use word-splitting to collapse spaces
else
    echo -e "Enabling single-user boot...\c"
    PV_ARGS=$(echo single $PV_ARGS)  # use word-splitting to collapse spaces
fi
if set_params vm "$VM_UUID" PV-args "$PV_ARGS"; then
    echo "done."
else
    exit 1
fi
