#!/bin/bash

function usage() {
    cat <<EOF

Set a VM's memory parameters.

Usage: ${0##*/} -s STATIC_MIN -S STATIC_MAX -d DYNAMIC_MIN -D DYNAMIC_MAX VM
EOF
    exit 2
}

MYDIR=$(dirname $0)
XS_FUNCTIONS="$MYDIR/xs-functions"
if ! . "$XS_FUNCTIONS"; then
    echo "Error while sourcing $XS_FUNCTIONS."
    exit 1
fi

unset STATIC_MIN STATIC_MAX DYNAMIC_MIN DYNAMIC_MAX
while getopts :s:S:d:D: OPT; do
    case $OPT in
        s)
            STATIC_MIN="$OPTARG"
            ;;
        S)
            STATIC_MAX="$OPTARG"
            ;;
        d)
            DYNAMIC_MIN="$OPTARG"
            ;;
        D)
            DYNAMIC_MAX="$OPTARG"
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
VM="$1"
shift
have_required STATIC_MIN STATIC_MAX DYNAMIC_MIN DYNAMIC_MAX VM || usage

VM_UUID=$(get_uuid vm "$VM") || exit 1
echo "VM UUID: $VM_UUID"

# can't use set_params() here because of constraints on memory parameters
xe vm-memory-limits-set uuid="$VM_UUID" \
    static-min="$STATIC_MIN" \
    dynamic-min="$DYNAMIC_MIN" \
    dynamic-max="$DYNAMIC_MAX" \
    static-max="$STATIC_MAX"
