#!/bin/bash

function usage() {
    cat <<EOF

Toggle a VM's "is-a-template" parameter.

Usage: ${0##*/} [-s] VM

-s    show the status of the VM's "is-a-template" parameter but don't modify
VM    name label of the VM to be modified
EOF
    exit 2
}

SHOW=0

while getopts :s OPT; do
    case $OPT in
        s)
            SHOW=1
            ;;
        *)
            usage
    esac
done
shift $(( OPTIND - 1 ))
[ -z "$1" ] || [ "$#" -gt 1 ] && usage
VM="$1"

VM_UUID=$(xe vm-list params=uuid name-label=$VM --minimal)
if [ -z "$VM_UUID" ]; then
    TEMPLATE_UUID=$(xe template-list params=uuid name-label=$VM --minimal)
    if [ -z "$TEMPLATE_UUID" ]; then
        echo "VM \"$VM\" not found"
        exit 1
    else
        if (( SHOW )); then
            IS="is"
        else
            if xe template-param-set is-a-template=false uuid="$TEMPLATE_UUID"; then
                IS="now is not"
            fi
        fi
    fi
else
    if (( SHOW )); then
        IS="is not"
    else
        if xe vm-param-set is-a-template=true uuid="$VM_UUID"; then
            IS="now is"
        fi
    fi
fi

if [ -n "$IS" ]; then
    echo "$VM $IS a template."
fi
